### ISSUE TITLE
App immediately exits on startup

### ISSUE THREAD

**Issue by Brandyn-Lobo** [Julioevm/tiny-scraper#1]
As written in the title, the app exits immediately. I have provided the log file.
[log.txt](https://github.com/user-attachments/files/17080699/log.txt)
I hope you can provide solution. the device is a Anbernic RG35XXSP with stockOS.

**Comment by Julioevm** [comment]
Can you share the version of the stock OS you have installed?

**Comment by Brandyn-Lobo** [comment]
V 1.0.3 (20240511)

**Comment by Julioevm** [comment]
I believe the issue is the old version you have installed. You will need to
update the OS.

**Comment by Julioevm** [comment]
Feel free to open another issue if the problem persist after updating!
